### ISSUE TITLE
Paginator cannot be imported nor is it declare globally

### ISSUE THREAD

**Issue by matsava** [lepikhinb/momentum-paginator#3]
I'm following your ebook on how to use typescript with inertia and vue.

I'm at a step where I would like to add a type to a paginated collection like so:
```
defineProps<{
    users: Paginator<App.Data.UserData> // Paginator here is undefined
}>()
```

The problem I am having is that the Paginator cannot be imported so my IDE is complaining that it isn't defined.

If I add the import then the paginator is defined but then I have an eslint issue screaming at me for an unused import
```
import { usePaginator } from "momentum-paginator";
```

I have no use of the Paginator in that Vue file because the pagination part is extracted into another component.

What would be the best approach here?

**Comment by lepikhinb** [comment]
You can extend your `tsconfig.json` to register the package's types globally. Add `momentum-paginator` to the array `types`.

```diff
{
  "compilerOptions": {
    "types": [
      "vite/client",
      "node",
+     "momentum-paginator"
    ],
  },
}
```

I hope this helps!

**Comment by matsava** [comment]
That was it! Thanks!
