### ISSUE TITLE
Discussion: Is this meant to be a Vue.js Composable or helper?

### ISSUE THREAD

**Issue by bitfactory-oussama-fadlaoui** [lepikhinb/momentum-paginator#5]
The way I see it, Vue.js composables will hook into components and/or other composables using Vue.js objects.

This package seems to use the naming convention of a composable, yet is not in fact a composable as it doesn't do any of the above mentioned things. I would like to contribute to update the package to be a composable if this is a wish of @lepikhinb.

**Comment by ricardov03** [comment]
Go ahead, and made the suggestion. I know @lepikhinb it's open to good ideas. I want to include support to others custom paginators. For example, I'm using this library to create my paginator: [PrimeVue Paginator](https://primevue.org/paginator/#api.paginator.props) I'm missing one parameter (Per Page) from this library, but could be nice if you can create plugins to feed any custom paginator.

**Comment by lepikhinb** [comment]
@bitfactory-oussama-fadlaoui thanks for the feedback.

VueUse (an officially supported library) provides a ton of utilities that follow the same naming convention yet have nothing to do with Vue.js objects (see: [https://vueuse.org/core/useNow/](https://vueuse.org/core/useNow)).

`usePaginator` returns an objects you'd usually love to **decompose**, so this kinda makes sense.

I would prefer keeping everything as is.
